package DataManager;
// Generated 2018-5-5 17:21:57 by Hibernate Tools 5.3.0.Beta2

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private String content;
	private Integer likes;
	private Integer publisher;
	private Integer item;

	public Comment() {
	}

	public Comment(String content, Integer likes, Integer publisher, Integer item) {
		this.content = content;
		this.likes = likes;
		this.publisher = publisher;
		this.item = item;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	public Integer getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Integer publisher) {
		this.publisher = publisher;
	}

	public Integer getItem() {
		return this.item;
	}

	public void setItem(Integer item) {
		this.item = item;
	}

}
