package DataManager;
// Generated 2018-5-6 18:05:34 by Hibernate Tools 5.3.0.Beta2

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private Integer id;
	private int owner;
	private String imageurl;
	private String location;
	private Integer likes;

	public Image() {
	}

	public Image(int owner, String imageurl) {
		this.owner = owner;
		this.imageurl = imageurl;
	}

	public Image(int owner, String imageurl, String location, Integer likes) {
		this.owner = owner;
		this.imageurl = imageurl;
		this.location = location;
		this.likes = likes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOwner() {
		return this.owner;
	}

	public void setOwner(int owner) {
		this.owner = owner;
	}

	public String getImageurl() {
		return this.imageurl;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getLikes() {
		return this.likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

}
