package DataManager;
// Generated 2018-5-5 17:21:57 by Hibernate Tools 5.3.0.Beta2

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String sex;
	private String birt;
	private String headurl;
	private String phone;
	private String emil;
	private String city;

	public User() {
	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public User(String username, String password, String sex, String birt, String headurl, String phone, String emil,
			String city) {
		this.username = username;
		this.password = password;
		this.sex = sex;
		this.birt = birt;
		this.headurl = headurl;
		this.phone = phone;
		this.emil = emil;
		this.city = city;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getBirt() {
		return this.birt;
	}

	public void setBirt(String birt) {
		this.birt = birt;
	}

	public String getHeadurl() {
		return this.headurl;
	}

	public void setHeadurl(String headurl) {
		this.headurl = headurl;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmil() {
		return this.emil;
	}

	public void setEmil(String emil) {
		this.emil = emil;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
