package DataManager;
// Generated 2018-12-18 10:02:08 by Hibernate Tools 5.2.10.Final

/**
 * ActorList generated by hbm2java
 */
public class ActorList implements java.io.Serializable {

	private Integer id;
	private Actor actor;
	private Movie movie;

	public ActorList() {
	}

	public ActorList(Actor actor, Movie movie) {
		this.actor = actor;
		this.movie = movie;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

}
