package DataManager;
// Generated 2018-12-18 10:02:08 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor implements java.io.Serializable {

	private Integer id;
	private String actorname;
	private String year;
	private String month;
	private String day;
	private String imageurl;
	private String sex;
	private String maoyanid;
	private Integer count;
	private Set actorCollects = new HashSet(0);
	private Set actorLists = new HashSet(0);

	public Actor() {
	}

	public Actor(String actorname, String year, String month, String day, String imageurl, String sex, String maoyanid,
			Integer count, Set actorCollects, Set actorLists) {
		this.actorname = actorname;
		this.year = year;
		this.month = month;
		this.day = day;
		this.imageurl = imageurl;
		this.sex = sex;
		this.maoyanid = maoyanid;
		this.count = count;
		this.actorCollects = actorCollects;
		this.actorLists = actorLists;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getActorname() {
		return this.actorname;
	}

	public void setActorname(String actorname) {
		this.actorname = actorname;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public String getImageurl() {
		return this.imageurl;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMaoyanid() {
		return this.maoyanid;
	}

	public void setMaoyanid(String maoyanid) {
		this.maoyanid = maoyanid;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Set getActorCollects() {
		return this.actorCollects;
	}

	public void setActorCollects(Set actorCollects) {
		this.actorCollects = actorCollects;
	}

	public Set getActorLists() {
		return this.actorLists;
	}

	public void setActorLists(Set actorLists) {
		this.actorLists = actorLists;
	}

}
