package DataManager;
// Generated 2018-12-18 10:02:08 by Hibernate Tools 5.2.10.Final

/**
 * ActorCollect generated by hbm2java
 */
public class ActorCollect implements java.io.Serializable {

	private Integer id;
	private Actor actor;
	private User user;

	public ActorCollect() {
	}

	public ActorCollect(Actor actor, User user) {
		this.actor = actor;
		this.user = user;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
