package DataManager;
// Generated 2018-12-18 10:02:08 by Hibernate Tools 5.2.10.Final

/**
 * Rating generated by hbm2java
 */
public class Rating implements java.io.Serializable {

	private Integer id;
	private Movie movie;
	private User user;
	private int rate;

	public Rating() {
	}

	public Rating(Movie movie, User user, int rate) {
		this.movie = movie;
		this.user = user;
		this.rate = rate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getRate() {
		return this.rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}

}
