package DataManager;
// Generated 2018-12-18 10:02:08 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String phone;
	private String username;
	private Set actorCollects = new HashSet(0);
	private Set ratings = new HashSet(0);

	public User() {
	}

	public User(String phone, String username) {
		this.phone = phone;
		this.username = username;
	}

	public User(String phone, String username, Set actorCollects, Set ratings) {
		this.phone = phone;
		this.username = username;
		this.actorCollects = actorCollects;
		this.ratings = ratings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Set getActorCollects() {
		return this.actorCollects;
	}

	public void setActorCollects(Set actorCollects) {
		this.actorCollects = actorCollects;
	}

	public Set getRatings() {
		return this.ratings;
	}

	public void setRatings(Set ratings) {
		this.ratings = ratings;
	}

}
